// Router
export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';
export const SET_NEW_USER = 'SET_NEW_USER';
export const SET_LOADING = 'SET_LOADING';
export const SET_THEME_INDEX = 'SET_THEME_INDEX';
export const RESET_ALL_REDUCER = 'RESET_ALL_REDUCER';
export const SET_SOCIAL_DRAWER_OPENED = 'SET_SOCIAL_DRAWER_OPENED';
export const SET_PROFILE_DRAWER_OPENED = 'SET_PROFILE_DRAWER_OPENED';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const API_CALLING = 'API_CALLING';
export const API_FINISHED = 'API_FINISHED';

// authentication
export const SET_SMS_VERIFY_STATUS = 'SET_SMS_VERIFY_STATUS';
export const COMPLETE_SIGN_UP = 'COMPLETE_SIGN_UP';
export const VERIFY_SMS = 'VERIFY_SMS';
export const SEND_SMS = 'SEND_SMS';

// Profile
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const UPDATE_BASIC_PROFILE = 'UPDATE_BASIC_PROFILE';
export const UPDATE_CONTACT_PROFILE = 'UPDATE_CONTACT_PROFILE';

// Reflection
export const GET_MY_REFLECTIONS = 'GET_MY_REFLECTIONS';
export const GET_USER_REFLECTIONS = 'GET_USER_REFLECTIONS';
export const SET_MY_REFLECTIONS = 'SET_MY_REFLECTIONS';
export const SET_USER_REFLECTIONS = 'SET_USER_REFLECTIONS';

// Feedback
export const GET_MY_FEEDBACKS = 'GET_MY_FEEDBACKS';
export const SET_MY_FEEDBACKS = 'SET_MY_FEEDBACKS';
export const GET_USER_FEEDBACKS = 'GET_USER_FEEDBACKS';
export const SET_USER_FEEDBACKS = 'SET_USER_FEEDBACKS';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const DESELECT_QUESTION = 'DESELECT_QUESTION';
export const SET_SELCTED_QUESTIONS = 'SET_SELCTED_QUESTIONS';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const REQUEST_FEEDBACK = 'REQUEST_FEEDBACK';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';

// Notifications
export const GET_NOTIFICATION_SETTINGS = 'GET_NOTIFICATION_SETTINGS';
export const SET_NOTIFICATION_SETTINGS = 'SET_NOTIFICATION_SETTINGS';
export const UPDATE_NOTIFICATION_SETTINGS = 'UPDATE_NOTIFICATION_SETTINGS';

// User, TrustMembers
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';
export const GET_ALL_TRUST_MEMBERS = 'GET_ALL_TRUST_MEMBERS';
export const SET_ALL_TRUST_MEMBERS = 'SET_ALL_TRUST_MEMBERS';
export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const SET_SELECTED_USERS = 'SET_SELECTED_USERS';
export const SET_SINGLE_SELECTED_USERS = 'SET_SINGLE_SELECTED_USERS';
export const SELECT_USER = 'SELECT_USER';
export const DESELECT_USER = 'DESELECT_USER';
export const DECLINE_USER_REQUEST = 'DECLINE_USER_REQUEST';

// Networks
export const GET_TRUST_NETWORKS = 'GET_TRUST_NETWORKS';
export const SET_TRUST_NETWORKS = 'SET_TRUST_NETWORKS';
export const INIT_TRUST_NETWORK = 'INIT_TRUST_NETWORK';
export const SELECT_TRUST_NETWORK = 'SELECT_TRUST_NETWORK';
export const UPDATE_SELECTED_TRUST_NETWORK = 'UPDATE_SELECTED_TRUST_NETWORK';
export const CREATE_TRUST_NETWORK = 'CREATE_TRUST_NETWORK';
export const UPDATE_TRUST_NETWORK = 'UPDATE_TRUST_NETWORK';
export const DELETE_TRUST_NETWORK = 'DELETE_TRUST_NETWORK';
