// Router
export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';
export const SET_NEW_USER = 'SET_NEW_USER';
export const SET_LOADING = 'SET_LOADING';
export const SET_THEME_INDEX = 'SET_THEME_INDEX';
export const RESET_ALL_REDUCER = 'RESET_ALL_REDUCER';
export const SET_SOCIAL_DRAWER_OPENED = 'SET_SOCIAL_DRAWER_OPENED';
export const SET_PROFILE_DRAWER_OPENED = 'SET_PROFILE_DRAWER_OPENED';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// authentication
export const SET_SMS_VERIFY_STATUS = 'SET_SMS_VERIFY_STATUS';
export const COMPLETE_SIGN_UP = 'COMPLETE_SIGN_UP';
export const VERIFY_SMS = 'VERIFY_SMS';
export const SEND_SMS = 'SEND_SMS';

// Profile
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const UPDATE_BASIC_PROFILE = 'UPDATE_BASIC_PROFILE';
export const UPDATE_CONTACT_PROFILE = 'UPDATE_CONTACT_PROFILE';

// Reflection
export const GET_MY_REFLECTIONS = 'GET_MY_REFLECTIONS';
export const GET_USER_REFLECTIONS = 'GET_USER_REFLECTIONS';
export const SET_MY_REFLECTIONS = 'SET_MY_REFLECTIONS';
export const SET_USER_REFLECTIONS = 'SET_USER_REFLECTIONS';

// Feedback
export const GET_MY_FEEDBACKS = 'GET_MY_FEEDBACKS';
export const SET_MY_FEEDBACKS = 'SET_MY_FEEDBACKS';
export const GET_USER_FEEDBACKS = 'GET_USER_FEEDBACKS';
export const SET_USER_FEEDBACKS = 'SET_USER_FEEDBACKS';

// Notifications
export const GET_NOTIFICATION_SETTINGS = 'GET_NOTIFICATION_SETTINGS';
export const SET_NOTIFICATION_SETTINGS = 'SET_NOTIFICATION_SETTINGS';
export const UPDATE_NOTIFICATION_SETTINGS = 'UPDATE_NOTIFICATION_SETTINGS';
