import {
  AnimalPeafowl,
  AnimalRockhopper,
  AnimalAlbatross,
  AnimalCat,
  AnimalChamois,
  AnimalChimpanzee,
  AnimalBat,
  AnimalPolarBear,
  AnimalSloth,
  AnimalSalmon,
  AnimalVulture,
  AnimalBear,
  AnimalWoodcock,
  AnimalBuffalo,
  AnimalTortoise,
  AnimalArmadillo,
  AnimalBee,
  AnimalCoral,
  AnimalElephant,
  AnimalFrog,
  AnimalGecko,
  AnimalHeron,
  AnimalHorse,
  AnimalJaguar,
  AnimalLemur,
  AnimalPuffer,
  AnimalSalamander,
  AnimalSeaTurtle,
  AnimalSparrowTwo,
  AnimalViper,
  AnimalBaboon,
  AnimalButterfly,
  AnimalElk,
  AnimalLeopard,
  AnimalMonkey,
  AnimalOctopus,
  AnimalTit,
  AnimalWarthog,
  AnimalWolf,
  AnimalWalrus,
} from '../assets/images';

// Constants used for testing

const getWeekNumber = d => {
  // Copy date so don't modify original
  d = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  // Set to nearest Thursday: current date + 4 - current day number
  // Make Sunday's day number 7
  d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7));
  // Get first day of year
  var yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  // Calculate full weeks to nearest Thursday
  var weekNo = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  // Return array of year and week number
  return weekNo;
};

export const FontFamilies = {
  bold: 'ProximaNovaA-Bold',
  regular: 'ProximaNova-Regular',
  thin: 'ProximaNovaT-Thin',
  italic: 'ProximaNova-RegularIt',
};

export const mainTabKeys = [
  'social',
  'resources',
  'progress',
  'tools',
  'profile',
];

export const ContactProfileKeys = [
  'preferredtobecalled',
  'namepronoun',
  'preferredpronoun',
  'email',
  'phone',
  'neighborhood',
];

export const WeekDays = [
  {
    long: 'Sunday',
    short: 'Sun',
  },
  {
    long: 'Monday',
    short: 'Mon',
  },
  {
    long: 'Tuesday',
    short: 'Tue',
  },
  {
    long: 'Wednesday',
    short: 'Wed',
  },
  {
    long: 'Thursday',
    short: 'Thu',
  },
  {
    long: 'Friday',
    short: 'Fri',
  },
  {
    long: 'Saturday',
    short: 'Sat',
  },
];

export const ProfileSideMenuList = [
  {
    index: 0,
    icon: 'link',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_signin',
    redirectTo: 'VerificationStack',
    registerRequired: false,
  },
  {
    index: 1,
    icon: 'sign-out',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_signout',
    redirectTo: '',
    registerRequired: true,
  },
  {
    index: 2,
    icon: 'sort',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_layout',
    redirectTo: 'ProfileLayout',
    registerRequired: true,
  },
  {
    index: 3,
    icon: 'cog',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_setting',
    redirectTo: 'Settings',
    registerRequired: true,
  },
  // {
  //   index: 4,
  //   icon: 'ios-send',
  //   iconType: 'Ionicon',
  //   title: 'profile_menu_cv',
  //   redirectTo: 'SendMochaCV',
  //   registerRequired: true,
  // },
  {
    index: 5,
    icon: 'bell',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_manage_notifications',
    redirectTo: 'ManageNotifications',
    registerRequired: true,
  },
  {
    index: 6,
    icon: 'dollar-sign',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_purchase',
    redirectTo: 'Purchase',
    registerRequired: true,
  },
  {
    index: 7,
    icon: 'minus-circle',
    iconType: 'FontAwesome5Pro',
    title: 'profile_menu_delete',
    redirectTo: '',
    registerRequired: true,
  },
];

export const ProfileSideSettingsList = [
  {
    index: 0,
    icon: 'phone',
    iconType: 'FontAwesome5Pro',
    title: 'settings_phone_number_update',
    redirectTo: 'PhoneUpdate',
    registerRequired: true,
  },
  {
    index: 1,
    icon: 'ios-calendar',
    iconType: 'Ionicon',
    title: 'profile_menu_timeline',
    redirectTo: 'TimeLine',
    registerRequired: true,
  },
  {
    index: 2,
    icon: 'ios-trending-up',
    iconType: 'Ionicon',
    title: 'profile_menu_analyze',
    redirectTo: 'Analyze',
    registerRequired: true,
  },
];

export const SampleFeedbackQuestions = [
  'mocha_feedback_handle-stress',
  'mocha_feedback_how-approachable',
  'mocha_feedback_how-coachable',
  'mocha_feedback_how-dependable',
  'mocha_feedback_how-trustworthy',
  'mocha_feedback_my-blindspots',
  'mocha_feedback_my-strenhths',
  'mocha_feedback_my-weakness',
  'mocha_feedback_when-i-was-at-best',
  'mocha_feedback_working-with-me',
  'mocha_feedback_best_self',
];

export const SocialPermissions = ['resources', 'progress'];

export const BasicPermissions = [
  'contact',
  'chronotype',
  'nutrition',
  'hydration',
  'stress_response',
  'strengths',
  'core_values',
  'dreams',
  'habits',
];

export const AdvancedPermissions = [
  'coaching_feedback',
  'criticism_feedback',
  'praise_feedback',
  'challenges_concerns',
  'qualities_character',
  'approach_to_conflict',
  'attachment_pattern',
  'comfort',
  'stress_recovery',
  'personality',
];

export const OthherPermissions = [
  'motivation',
  'manual',
  'value',
  'emotion',
  'need',
  'personal_story',
  'risk_tolerance',
  'meaning_life',
];

export const NightSliderValues = [
  '7:00 PM',
  '8:00 PM',
  '9:00 PM',
  '10:00 PM',
  '11:00 PM',
  '00:00 AM',
  '01:00 AM',
  '02:00 AM',
  '03:00 AM',
  '04:00 AM',
  '05:00 AM',
  '06:00 AM',
  '07:00 AM',
];
export const DaySliderValues = [
  '7:00 AM',
  '8:00 AM',
  '9:00 AM',
  '10:00 AM',
  '11:00 AM',
  '12:00 PM',
  '01:00 PM',
  '02:00 PM',
  '03:00 PM',
  '04:00 PM',
  '05:00 PM',
  '06:00 PM',
  '07:00 PM',
];

export const PostChallengeLevels = [
  'low',
  'low-medium',
  'medium',
  'medium-high',
  'high',
];

export const PostMoraleLevels = [
  'low',
  'low-medium',
  'medium',
  'medium-high',
  'high',
];

export const HydrationValues = ['2', '3', '4', '5', '6', '7', '8+'];

export const SampleReflectionSections = {
  needs: [
    'for-admiration',
    'for-advice',
    'for-affection',
    'for-alignment',
    'for-assurance',
    'for-attachment',
    'for-autonomy',
    'for-beauty',
    'for-bravery',
    'for-calm',
    'for-catharsis',
    'for-certainty',
    'for-challenge',
    'for-clarity',
    'for-clarity-in-my-thoughts',
    'for-cleanliness',
    'for-closeness',
    'for-combat',
    'for-compassion',
    'for-competence',
    'for-competition',
    'for-consistency',
    'for-context',
    'for-control',
    'for-courage',
    'for-disconnection',
    'for-effectiveness',
    'for-emotional-release',
    'for-emotional-security',
    'for-empathy',
    'for-emptiness',
    'for-escape',
    'for-excellence',
    'for-exploration',
    'for-fairness',
    'for-fear',
    'for-focus',
    'for-freedom',
    'for-friendship',
    'for-fun',
    'for-glory',
    'for-growth',
    'for-honesty',
    'for-honor',
    'for-inconsistency',
    'for-integration',
    'for-irrelevance',
    'for-justice',
    'for-kindness',
    'for-laughter',
    'for-music',
    'for-nature',
    'for-novelty',
    'for-order',
    'for-physical-touch',
    'for-play',
    'for-pleasure',
    'for-power',
    'for-privacy',
    'for-quiet',
    'for-rawness',
    'for-reassurance',
    'for-reciprocation',
    'for-release',
    'for-relevance',
    'for-respect',
    'for-rest',
    'for-routine',
    'for-sanity',
    'for-self-actualization',
    'for-self-care',
    'for-self-esteem',
    'for-self-love',
    'for-self-respect',
    'for-self-understanding',
    'for-sex',
    'for-significance',
    'for-spontaneity',
    'for-stability',
    'for-status',
    'for-subtly',
    'for-superiority',
    'for-symmetry',
    'for-tenderness',
    'for-things-to-make-sense',
    'for-transcendence',
    'for-uncertainty',
    'for-understanding',
    'for-union',
    'for-validation',
    'for-variety',
    'to-belong',
    'to-build-trust',
    'to-care-for-my-family',
    'to-control',
    'to-create',
    'to-do-my-part',
    'to-dream',
    'to-empower',
    'to-escape',
    'to-escape-from-sadness',
    'to-escape-from-seriousness',
    'to-feel-I’m-growing',
    'to-feel-I’ve-grown',
    'to-feel-affection',
    'to-feel-afraid',
    'to-feel-alignment',
    'to-feel-alive',
    'to-feel-appreciated',
    'to-feel-attached',
    'to-feel-attractive',
    'to-feel-autonomous',
    'to-feel-belonging',
    'to-feel-brave',
    'to-feel-calm',
    'to-feel-capable',
    'to-feel-cared-for',
    'to-feel-certain',
    'to-feel-challenged',
    'to-feel-cherished',
    'to-feel-clean',
    'to-feel-clever',
    'to-feel-close',
    'to-feel-coached',
    'to-feel-comforted',
    'to-feel-compassion',
    'to-feel-competent',
    'to-feel-competitive',
    'to-feel-content',
    'to-feel-contentment',
    'to-feel-controlled',
    'to-feel-controlling',
    'to-feel-courageous',
    'to-feel-creative',
    'to-feel-deeply',
    'to-feel-disconnected',
    'to-feel-distressed',
    'to-feel-dominated',
    'to-feel-effective',
    'to-feel-unburdened',
    'to-feel-empathized-with',
    'to-feel-empowered',
    'to-feel-empty',
    'to-feel-encouraged',
    'to-feel-excellent',
    'to-feel-excited',
    'to-feel-excitement',
    'to-feel-exhausted',
    'to-feel-explored',
    'to-feel-exposed',
    'to-feel-like-a-fool',
    'to-feel-focused',
    'to-feel-free',
    'to-feel-free-from-blame',
    'to-feel-free-from-mistakes',
    'to-feel-fully-integrated',
    'to-feel-giving',
    'to-feel-glorious',
    'to-feel-heard',
    'to-feel-hidden',
    'to-feel-honest',
    'to-feel-humiliated',
    'to-feel-important',
    'to-feel-in-alignment',
    'to-feel-in-control',
    'to-feel-in-order',
    'to-feel-in-the-right',
    'to-feel-inconsistent',
    'to-feel-integrated',
    'to-feel-kindness',
    'to-feel-like-I-matter',
    'to-feel-like-a-friend',
    'to-feel-like-a-good-person',
    'to-feel-like-my-work-matters',
    'to-feel-listened-to',
    'to-feel-loved',
    'to-feel-loved-just-as-I-am',
    'to-feel-moral',
    'to-feel-my-contributions-matter',
    'to-feel-my-services-matter',
    'to-feel-natural',
    'to-feel-needed',
    'to-feel-order',
    'to-feel-original',
    'to-feel-out-of-control',
    'to-feel-perfect',
    'to-feel-physically-touched',
    'to-feel-powerful',
    'to-feel-provided-for',
    'to-feel-pushed-faster',
    'to-feel-pushed-harder',
    'to-feel-reciprocated-for',
    'to-feel-reckless',
    'to-feel-recognized',
    'to-feel-released',
    'to-feel-relevant',
    'to-feel-respected',
    'to-feel-right',
    'to-feel-sad',
    'to-feel-safe',
    'to-feel-sane',
    'to-feel-seen',
    'to-feel-selfless',
    'to-feel-sexual',
    'to-feel-significant',
    'to-feel-soothed',
    'to-feel-special',
    'to-feel-stable',
    'to-feel-subtle',
    'to-feel-superior',
    'to-feel-that-I-matter',
    'to-feel-touched',
    'to-feel-tranquil',
    'to-feel-trusted',
    'to-feel-uncertain',
    'to-feel-uncomfortable',
    'to-feel-understood',
    'to-feel-unique',
    'to-feel-various',
    'to-feel-vulnerable',
    'to-feel-wanted',
    'to-feel-worthy',
    'to-feel-worthy-of-existing',
    'to-feel-young',
    'to-find-excitement',
    'to-finish-what-I-started',
    'to-give',
    'to-give-it-my-all',
    'to-have-a-voice',
    'to-have-my-voice-heard',
    'to-have-an-impact',
    'to-listen',
    'to-love',
    'to-love-another',
    'to-matter',
    'to-meet-high-standards',
    'to-play',
    'to-please-my-family',
    'to-raise-my-standards',
    'to-reduce-my-anxiety',
    'to-say-I-told-you-so',
    'to-see-the-world',
    'to-serve',
    'to-show-gratitude',
    'to-take-care-of-my-family',
    'to-take-risks',
    'to-talk',
  ],
  manuals: [
    'good-at',
    'need-help',
    'preferred-help-style',
    'values',
    'want-learn',
    'respond-under-stress',
    'misunderstand',
    'look-disagree',
    'work-condition',
    'time-to-work',
    'communicate-style',
    'feedback-style',
    'needs',
    'love',
  ],
  feedbacks: [
    'my-strenths',
    'my-weakness',
    'my-blindspots',
    'working-with-me',
    'when-i-was-at-best',
    'handle-stress',
    'how-approachable',
    'how-coachable',
    'how-dependable',
    'how-trustworthy',
  ],
};

export const EMOTIONS = [
  ['anger', 'sadness', 'surprise', 'joy', 'love', 'fear'],
  [
    'anger_enraged',
    'anger_exasperated',
    'anger_irritable',
    'anger_envious',
    'anger_disgusted',
    'sadness_distressed',
    'sadness_melancholic',
    'sadness_disappointed',
    'sadness_shameful',
    'sadness_neglected',
    'sadness_hopeless',
    'surprise_stunned',
    'surprise_confused',
    'surprise_amazed',
    'surprise_overcome',
    'surprise_moved',
    'joy_content',
    'joy_happy',
    'joy_cheerful',
    'joy_proud',
    'joy_optimistic',
    'joy_enthusiastic',
    'joy_elated',
    'joy_enthralled',
    'love_desirous',
    'love_romantic',
    'love_longing',
    'love_tender',
    'love_peaceful',
    'fear_scared',
    'fear_terrified',
    'fear_insecure',
    'fear_nervous',
    'fear_horrified',
  ],
  [
    'anger_enraged_hateful',
    'anger_enraged_hostile',
    'anger_exasperated_agitated',
    'anger_exasperated_frustrated',
    'anger_irritable_annoyed',
    'anger_irritable_aggravated',
    'anger_envious_resentful',
    'anger_envious_jealout',
    'anger_disgusted_contemptuous',
    'anger_disgusted_revolted',
    'sadness_distressed_agonized',
    'sadness_distressed_hurt',
    'sadness_melancholic_depressed',
    'sadness_melancholic_sorrowful',
    'sadness_disappointed_dismayed',
    'sadness_disappointed_displeased',
    'sadness_shameful_regretful',
    'sadness_shameful_guilty',
    'sadness_neglected_isolated',
    'sadness_neglected_lonely',
    'sadness_hopeless_anguished',
    'sadness_hopeless_powerless',
    'surprise_stunned_shocked',
    'surprise_stunned_dismayed',
    'surprise_confused_disillusioned',
    'surprise_confused_perplexed',
    'surprise_amazed_astonished',
    'surprise_amazed_awe-struck',
    'surprise_overcome_speechless',
    'surprise_overcome_astounded',
    'surprise_moved_stimulated',
    'surprise_moved_touched',
    'joy_content_thankful',
    'joy_content_pleased',
    'joy_happy_amused',
    'joy_happy_delighted',
    'joy_cheerful_jovial',
    'joy_cheerful_playful',
    'joy_proud_trimphant',
    'joy_proud_illustrious',
    'joy_optimistic_eager',
    'joy_optimistic_hopeful',
    'joy_enthusiastic_excited',
    'joy_enthusiastic_zealous',
    'joy_elated_euphoric',
    'joy_elated_jubilant',
    'joy_enthralled_enchanted',
    'joy_enthralled_rapturous',
    'love_desirous_passionate',
    'love_desirous_infatuated',
    'love_romantic_attractive',
    'love_romantic_enamored',
    'love_longing_sentimental',
    'love_longing_affectionate',
    'love_tender_caring',
    'love_tender_compassionate',
    'love_peaceful_tranquil',
    'love_peaceful_satisfied',
    'fear_scared_frightened',
    'fear_scared_helpless',
    'fear_terrified_panic',
    'fear_terrified_hysterical',
    'fear_insecure_inferior',
    'fear_insecure_indadequate',
    'fear_nervous_worried',
    'fear_nervous_anxious',
    'fear_horrified_mortified',
    'fear_horrified_dreadful',
  ],
];

export const EmotionHow = ['midly', 'moderately', 'intensely', 'hysterically'];

export const ReflectionKeys = [
  'Chronotype',
  'Nutrition',
  'Hydration',
  'StressRecovery',
  'Strengths',
  'CoreValues',
  'Dreams',
  'Habit',
  'CoachingFeedback',
  'CriticismFeedback',
  'PraiseFeedback',
  'Qualities',
  'Challenges',
  'Approach',
  'Attachment',
  'Comfort',
  'MeaningLife',
  'Personality',
  'Value',
  'Purpose',
  'Motivation',
  'Languages',
  'Manual',
  'Risks',
  'Quirks',
  'Triggers',
];

export const DefaultReflections = {
  motivation: {
    type: 'Motivation',
    data: {
      title: '',
      description: '',
      image: '',
    },
  },
  manual: {
    type: 'Manual',
    data: {
      title: '',
      text: '',
      vulnerability: 1,
      tags: [],
      image: '',
    },
  },
  chronotype: {
    type: 'Chronotype',
    data: {
      type: 'morning', // morning, flexible, night
      night_sleep_offset_start: 3, // 0 ~ 12
      night_sleep_offset_end: 10, // 0 ~ 12
      day_sleep_offset_start: 5, // 0 ~ 12
      day_sleep_offset_end: 7, // 0 ~ 12
    },
  },
  value: {
    type: 'Value',
    data: {
      value: '',
      phrase: '',
      learn: '',
      image: '',
      action: '',
    },
  },
  emotion: {
    type: 'Emotion',
    data: {
      emotion: EMOTIONS[2][0],
      how: EmotionHow[0],
      story: '',
    },
  },
  habit: {
    type: 'Habit',
    data: {
      title: '',
      habits: [],
      isDaily: false,
      deadline: 6,
      weekNum: getWeekNumber(new Date()),
      collaborators: [],
      love: 0,
      nudge: 0,
      strong: 0,
      cheer: 0,
      congrats: 0,
      crown: 0,
    },
  },
  need: {
    type: 'Need',
    data: {
      need: '',
      value: '',
      reason: '',
    },
  },
  personality: {
    type: 'Personality',
    data: {
      honest_humility: 0,
      emotionality: 0,
      extraversion: 0,
      agreeableness: 0,
      conscientiousness: 0,
      openness_to_experience: 0,
    },
  },
  personalstory: {
    type: 'PersonalStory',
    data: {
      pronounce: '', // file path
      hometown: '',
      number_of_kids: 1,
      childhood_hobbies: [],
      first_job: '',
      biggest_challenge: '',
    },
  },
  risk_tolerance: {
    type: 'RiskTolerance',
    data: {
      options: [],
    },
  },
  attachment: {
    type: 'Attachment',
    data: {
      options: [],
    },
  },
  core_values: {
    type: 'CoreValues',
    data: {
      selected: [],
      core: [],
      custom: [],
      story: {},
    },
  },
  approach: {
    type: 'Approach',
    data: {
      options: [],
    },
  },
  stress_response: {
    type: 'StressResponse',
    data: {
      parts: [],
    },
  },
  nutrition: {
    type: 'Nutrition',
    data: {
      best: [],
      worst: [],
    },
  },
  hydration: {
    type: 'Hydration',
    data: {
      cups_range: [1, 4],
      practices: [],
    },
  },
  strengths: {
    type: 'Strengths',
    data: {
      options: [],
    },
  },
  dreams: {
    type: 'Dreams',
    data: {
      main: '',
      others: [],
    },
  },
  challenges: {
    type: 'Challenges',
    data: {
      pleasing: 50,
      optimistic: 50,
      defensive: 50,
      high_emotionality: 50,
      cynical: 50,
      procrasinators: 50,
      immature: 50,
      teachers: 50,
      naysayers: 50,
      paranoid: 50,
      charmless: 50,
      frank: 50,
      bookmarked: [],
    },
  },
  qualities: {
    type: 'Qualities',
    data: {
      ownership: 50,
      flexible: 50,
      punctual: 50,
      optimistic: 50,
      criticism: 50,
      creative: 50,
      sense_of_humor: 50,
      listener: 50,
      storyteller: 50,
      emotional_intelligence: 50,
      integrity: 50,
      conscientiousness: 50,
      bookmarked: [],
    },
  },
  coaching_feedback: {
    type: 'CoachingFeedback',
    data: {
      options: [],
    },
  },
  criticism_feedback: {
    type: 'CriticismFeedback',
    data: {
      options: [],
    },
  },
  praise_feedback: {
    type: 'PraiseFeedback',
    data: {
      options: [],
    },
  },
  comfort: {
    type: 'Comfort',
    data: {
      options: [],
    },
  },
  stress_recovery: {
    type: 'StressRecovery',
    data: {
      methods: [],
    },
  },
  meaning_life: {
    type: 'MeaningLife',
    data: {
      options: [],
    },
  },
};

export const ResourceTypes = [
  {
    type: 'book',
    icon: 'book',
  },
  {
    type: 'article',
    icon: 'book-reader',
  },
  {
    type: 'video',
    icon: 'video',
  },
  {
    type: 'podcast',
    icon: 'podcast',
  },
  {
    type: 'class',
    icon: 'question',
  },
  {
    type: 'blog',
    icon: 'blog',
  },
  {
    type: 'event',
    icon: 'rss-square',
  },
  {
    type: 'author',
    icon: 'user-edit',
  },
];

export const AnalyzeDummyData = {
  '20190305': 2,
  '20190506': 6,
  '20200120': 10,
  '20200122': 20,
  '20200123': 30,
  '20200303': 1,
  '20200308': 10,
  '20200313': 9,
  '20200320': 1,
  '20200323': 12,
  '20200325': 5,
};

export const ProfileBasicCards = {
  chronotype: {
    title: 'sleep_chronotype',
    minutes: 2,
    width: 250,
    redirectTo: 'PB_SleepChronotype',
  },
  nutrition: {
    title: 'nutrition',
    minutes: 3,
    width: 150,
    redirectTo: 'PB_Nutrition',
  },
  hydration: {
    title: 'hydration',
    minutes: 2,
    width: 150,
    redirectTo: 'PB_Hydration',
  },
  stress: {
    title: 'stress_response',
    minutes: 6,
    width: 250,
    redirectTo: 'PB_StressResponse',
  },
  strength: {
    title: 'strengths',
    minutes: 3,
    width: 250,
    redirectTo: 'PB_Strengths',
  },
  values: {
    title: 'core_values',
    minutes: 15,
    width: 250,
    redirectTo: 'PB_DiscoverValue',
  },
  dream: {
    title: 'dreams',
    minutes: 5,
    width: 250,
    redirectTo: 'PB_Dream',
  },
  habit: {
    title: 'habits',
    minutes: 5,
    width: 250,
    redirectTo: 'PB_SetHabit',
  },
};

export const ProfileAdvanceCards = {
  coaching_feedback: {
    title: 'coaching_feedback',
    minutes: 2,
    width: 250,
    redirectTo: 'PA_Coaching',
  },
  criticism_feedback: {
    title: 'criticism_feedback',
    minutes: 4,
    width: 150,
    redirectTo: 'PA_Criticism',
  },
  praise_feedback: {
    title: 'praise_feedback',
    minutes: 4,
    width: 150,
    redirectTo: 'PA_Praise',
  },
  qualities_character: {
    title: 'qualities_character',
    minutes: '4~6',
    width: 250,
    redirectTo: 'PA_Qualities_Character',
  },
  challenges_concerns: {
    title: 'challenges_concerns',
    minutes: '4~6',
    width: 250,
    redirectTo: 'PA_Challenges_Concerns',
  },
  approach: {
    title: 'approach_to_conflict',
    minutes: 2,
    width: 250,
    redirectTo: 'PA_Approach',
  },
  attachment: {
    title: 'attachment_pattern',
    minutes: 2,
    width: 150,
    redirectTo: 'PA_Attachment',
  },
  comforting: {
    title: 'comfort',
    minutes: 2,
    width: 150,
    redirectTo: 'PA_Comforting',
  },
  stress_recovery: {
    title: 'stress_recovery',
    minutes: 4,
    width: 250,
    redirectTo: 'PA_StressRecovery',
  },
};

export const ProfileExpertCards = {
  core_values: {
    title: 'personalize_value',
    minutes: '15~30',
    width: 250,
    redirectTo: 'PE_Personalize_CoreValue',
  },
  strength: {
    title: 'best_self',
    minutes: 30,
    width: 250,
    redirectTo: 'PE_BestSelf',
  },
  meaning: {
    title: 'meaning_of_life',
    minutes: 5,
    width: 250,
    redirectTo: 'PE_MeaningLife',
  },
};

export const NegativeFeedbackPreferences = [
  'private',
  'public',
  'written_or_email',
  'face',
  'immediately',
  'closed_door_meeting',
  'detailed_explanation',
  'clear_and_specific',
  'facts_and_data',
  'do_not_give',
  'reassuringly',
  'soften_the_blow',
  'empathatically',
  'supportively',
  'template',
];

export const PositiveFeedbackPreferences = [
  'private',
  'public',
  'written_or_email',
  'face',
  'facts_and_data',
  'immediately',
  'explaning_impact',
  'clear_and_specific',
  'focus_on_effort',
  'focus_on_impact',
  'once_a_week',
  'once_a_month',
  'individual_focused',
  'team_focused',
  'hard_skills_focused',
  'soft_skills_focused',
];

export const BehaviorPreferences = [
  'ownership',
  'flexible',
  'punctual',
  'optimistic',
  'criticism',
  'creative',
  'sense_of_humor',
  'listener',
  'storyteller',
  'emotional_intelligence',
  'integrity',
  'conscientiousness',
];

export const BehaviorPreferenceNegatives = [
  'pleasing',
  'optimistic',
  'defensive',
  'high_emotionality',
  'cynical',
  'procrasinators',
  'immature',
  'teachers',
  'naysayers',
  'paranoid',
  'charmless',
  'frank',
];

export const RiskTolerances = [
  'driving_fast',
  'business',
  'kitesurfing',
  'driving_shark',
  'gambling',
  'live_regret',
  'fly',
  'rock_climbing',
  'training_race',
  'alone',
  'people',
];

export const AttachmentOptions = [
  'avoidant',
  'anxious',
  'secure',
  'anxious_and_avoidant',
];

export const profileIcons = [
  {
    key: 'overview',
    iconType: 'FontAwesome5',
    icon: 'pen-alt',
    signinRequired: false,
    edit_disabled: true,
    hasSvg: false,
  },
  {
    key: 'contact',
    iconType: 'FontAwesome5',
    icon: 'phone',
    signinRequired: false,
    hasSvg: false,
  },
  {
    key: 'chronotype',
    iconType: 'FontAwesome5Pro',
    icon: 'sheep',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'nutrition',
    iconType: 'FontAwesome5Pro',
    icon: 'carrot',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'hydration',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'stress_recovery',
    iconType: 'FontAwesome5Pro',
    icon: 'fragile',
    signinRequired: true,
    hasSvg: true,
  },
  {
    key: 'strengths',
    iconType: 'FontAwesome5Pro',
    icon: 'hammer',
    signinRequired: true,
    hasSvg: false,
  },
  {
    key: 'core_values',
    iconType: 'FontAwesome5Pro',
    icon: 'key',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'dreams',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'habits',
    iconType: 'FontAwesome5Pro',
    icon: 'apple-alt',
    signinRequired: true,
    hasSvg: true,
  },
  {
    key: 'coaching_feedback',
    iconType: 'FontAwesome5Pro',
    icon: 'bullhorn',
    signinRequired: true,
    hasSvg: true,
  },
  {
    key: 'criticism_feedback',
    iconType: 'FontAwesome5Pro',
    icon: 'hand-point-down',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'praise_feedback',
    iconType: 'FontAwesome5Pro',
    icon: 'award',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'qualities_character',
    iconType: 'FontAwesome5Pro',
    icon: 'medal',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'challenges_concerns',
    iconType: 'FontAwesome5Pro',
    icon: 'exclamation-triangle',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'approach_to_conflict',
    iconType: 'FontAwesome5Pro',
    icon: 'boxing-glove',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'attachment_pattern',
    iconType: 'Ionicon',
    icon: 'ios-attach',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'comfort',
    iconType: 'FontAwesome5Pro',
    icon: 'hand-heart',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'meaning_life',
    iconType: 'FontAwesome5Pro',
    icon: 'skull-cow',
    signinRequired: false,
    hasSvg: true,
  },
  {
    key: 'personality',
    iconType: 'Ionicon',
    icon: 'ios-finger-print',
    signinRequired: false,
    hasSvg: false,
  },
  {
    key: 'feedbacks',
    iconType: 'Ionicon',
    icon: 'ios-git-compare',
    signinRequired: false,
    hasSvg: false,
  },
  {
    key: 'purposes',
    iconType: 'Ionicon',
    icon: 'ios-body',
    signinRequired: true,
    hasSvg: false,
  },
  {
    key: 'motivations',
    iconType: 'Ionicon',
    icon: 'ios-fitness',
    signinRequired: false,
    hasSvg: false,
  },
  {
    key: 'languages',
    iconType: 'Ionicon',
    icon: 'ios-heart',
    signinRequired: true,
    hasSvg: false,
  },
  {
    key: 'beliefs',
    iconType: 'Ionicon',
    icon: 'ios-cloud-upload',
    signinRequired: false,
    hasSvg: false,
  },
  {
    key: 'risks',
    iconType: 'FontAwesome5',
    icon: 'skiing',
    signinRequired: true,
    hasSvg: false,
  },
  {
    key: 'quirks',
    iconType: 'Ionicon',
    icon: 'ios-bowtie',
    signinRequired: true,
    hasSvg: false,
  },
  {
    key: 'triggers',
    iconType: 'Ionicon',
    icon: 'ios-warning',
    signinRequired: true,
    hasSvg: false,
  },
];

export const ApproachToConflictOptions = [
  'peace_keeping',
  'avoid_withdraw',
  'learning_embracing',
  'high_emotion',
  'direct_aggression',
  'compromising',
  'indirect_aggression',
  'collaborating',
  'competing',
  'yeild',
  'stand_my_ground',
  'curious',
  'self_assertive',
  'self_blaming',
];

export const MeaningLifeOptions = [
  'friend_family_love',
  'creativity',
  'self-improvement',
  'music',
  'other_services',
  'connection',
  'belonging',
  'trancendence',
  'self-knowledge',
  'order',
];

export const CommitColors = ['#99AA99', '#669966', '#11BB11', '#00FF00'];
export const ValueCardTextColor = '#222222';
export const ValueCardBackgrounds = ['#FBE9E6', '#E9F6F9', '#E5E6E8'];

export const DiscoverValues = [
  {
    value: 'beauty',
    category: 'universalism',
    name: 'indian_peafowl',
    image: AnimalPeafowl,
  },
  {
    value: 'daring',
    category: 'simulation',
    name: 'rockhopper',
    image: AnimalRockhopper,
  },
  {
    value: 'freedom',
    category: 'self-direction',
    name: 'albatross',
    image: AnimalAlbatross,
  },
  {
    value: 'exciting_life',
    category: 'stimulation',
    name: 'chamois',
    image: AnimalChamois,
  },
  {
    value: 'humor',
    category: 'security',
    name: 'chimpanzee',
    image: AnimalChimpanzee,
  },
  {
    value: 'reciprocation',
    category: 'security',
    name: 'bat',
    image: AnimalBat,
  },
  {
    value: 'family_security',
    category: 'security',
    name: 'polar_bear',
    image: AnimalPolarBear,
  },
  {
    value: 'unity_with_nature',
    category: 'universalism',
    name: 'sloth',
    image: AnimalSloth,
  },
  {
    value: 'meaning_in_life',
    category: 'benevolence',
    name: 'salmon',
    image: AnimalSalmon,
  },
  {
    value: 'spiritual_life',
    category: 'benevolence',
    name: 'vulture',
    image: AnimalVulture,
  },
  {
    value: 'self_indulgence',
    category: 'hedonism',
    name: 'grizzly_bear',
    image: AnimalBear,
  },
  {
    value: 'humility',
    category: 'tradition',
    name: 'woodcock',
    image: AnimalWoodcock,
  },
  {
    value: 'respect_for_tradition',
    category: 'tradition',
    name: 'american_bison',
    image: AnimalBuffalo,
  },
  {
    value: 'wisdom',
    category: 'universalism',
    name: 'tortoise',
    image: AnimalTortoise,
  },
  {
    value: 'sense',
    category: 'security',
    name: 'arctic_walrus',
    image: AnimalWalrus,
  },
  {
    value: 'respect',
    category: 'achievement',
    name: 'domestic_cat',
    image: AnimalCat,
  },
  {
    value: 'equality',
    category: 'achievement',
    name: 'armadillo',
    image: AnimalArmadillo,
  },
  {
    value: 'acceptance_life',
    category: 'tradition',
    name: 'bee',
    image: AnimalBee,
  },
  {
    value: 'influence',
    category: 'achievement',
    name: 'coral',
    image: AnimalCoral,
  },
  {
    value: 'social_justice',
    category: 'universalism',
    name: 'elephant',
    image: AnimalElephant,
  },
  {
    value: 'politeness',
    category: 'conformity',
    name: 'frog',
    image: AnimalFrog,
  },
  {
    value: 'cleanliness',
    category: 'security',
    name: 'gecko',
    image: AnimalGecko,
  },
  {
    value: 'inner_harmony',
    category: 'universalism',
    name: 'heron',
    image: AnimalHeron,
  },
  {
    value: 'honesty',
    category: 'benevolence',
    name: 'horse',
    image: AnimalHorse,
  },
  {
    value: 'privacy',
    category: 'self-direction',
    name: 'jaguar',
    image: AnimalJaguar,
  },
  {
    value: 'national_security',
    category: 'security',
    name: 'lemur',
    image: AnimalLemur,
  },
  {
    value: 'creativity',
    category: 'self-direction',
    name: 'puffer',
    image: AnimalPuffer,
  },
  {
    value: 'health',
    category: 'security',
    name: 'salamander',
    image: AnimalSalamander,
  },
  {
    value: 'devoutness',
    category: 'tradition',
    name: 'sea_turtle',
    image: AnimalSeaTurtle,
  },
  {
    value: 'social',
    category: 'power',
    name: 'sparrow_2',
    image: AnimalSparrowTwo,
  },
  {
    value: 'independence',
    category: 'self-direction',
    name: 'viper',
    image: AnimalViper,
  },
  {
    value: 'social_order',
    category: 'security',
    name: 'baboon',
    image: AnimalBaboon,
  },
  {
    value: 'varied_life',
    category: 'stimulation',
    name: 'butterfly',
    image: AnimalButterfly,
  },
  {
    value: 'authority',
    category: 'power',
    name: 'elk',
    image: AnimalElk,
  },
  {
    value: 'self_discipline',
    category: 'conformity',
    name: 'leopard',
    image: AnimalLeopard,
  },
  {
    value: 'respect_parent',
    category: 'conformity',
    name: 'monkey',
    image: AnimalMonkey,
  },
  {
    value: 'capability',
    category: 'achievement',
    name: 'octopus',
    image: AnimalOctopus,
  },
  {
    value: 'obedience',
    category: 'conformity',
    name: 'tit',
    image: AnimalTit,
  },
  {
    value: 'boldness',
    category: 'self-direction',
    name: 'warthog',
    image: AnimalWarthog,
  },
  {
    value: 'broad_mindedness',
    category: 'universalism',
    name: 'wolf',
    image: AnimalWolf,
  },
];

export const ToolsSideTabs = [
  {
    key: 'favorites',
    iconType: 'FontAwesome5',
    icon: 'star',
  },
  {
    key: 'body',
    iconType: 'FontAwesome5Pro',
    icon: 'dumbbell',
  },
  {
    key: 'mind',
    iconType: 'FontAwesome5Pro-Light',
    icon: 'brain',
  },
  {
    key: 'social',
    iconType: 'FontAwesome5Pro',
    icon: 'comments-alt',
  },
  {
    key: 'search',
    iconType: 'FontAwesome5Pro-Light',
    icon: 'search',
  },
];

export const HydrationPracticeOptions = [
  'thirsty',
  'regular',
  'electrolyte',
  'hot',
  'cold',
  'clear',
  'forgetful',
  'bliss',
];

export const StrengthOptions = [
  {
    key: 'interpersonal',
    iconType: 'FontAwesome5Pro',
    icon: 'handshake',
    width: 150,
  },
  {
    key: 'linguistic',
    iconType: 'FontAwesome5Pro',
    icon: 'podium',
    width: 150,
  },
  {
    key: 'bodily',
    iconType: 'FontAwesome5Pro',
    icon: 'skiing',
    width: 150,
  },
  {
    key: 'spatial',
    iconType: 'FontAwesome5Pro',
    icon: 'map-marked-alt',
    width: 150,
  },
  {
    key: 'intra-personal',
    iconType: 'FontAwesome5Pro',
    icon: 'mind-share',
    width: 150,
  },
  {
    key: 'musical',
    iconType: 'FontAwesome5Pro',
    icon: 'guitar',
    width: 150,
  },
  {
    key: 'naturalist',
    iconType: 'FontAwesome5Pro',
    icon: 'seedling',
    width: 150,
  },
  {
    key: 'logical',
    iconType: 'FontAwesome5Pro',
    icon: 'function',
    width: 150,
  },
  {
    key: 'existential',
    iconType: 'FontAwesome5Pro',
    icon: 'books',
    width: 150,
  },
];

export const skills = [
  'empathy',
  'service',
  'curiosity',
  'leadership',
  'character_development',
  'transcendence',
  'humility',
  'courage',
  'perspective_taking',
  'forgiveness',
  'community',
  'belonging',
  'citizenship',
  'optimism',
  'spirituality',
  'self_control',
  'appreciation_of_beauty',
  'social_intelligence',
  'kindness',
  'gratitude',
  'integrity',
  'prudence',
  'humor',
  'perseverance',
  'love_of_learning',
  'influence',
  'persuasion',
  'confidence',
  'psychology',
  'public_speaking',
  'thinking',
  'critical_thinking',
];

export const impacts = [
  {
    key: 1,
    value: 'impactful',
  },
  {
    key: 2,
    value: 'therapeutic',
  },
  {
    key: 3,
    value: 'self_discovery',
  },
  {
    key: 4,
    value: 'cathartic',
  },
  {
    key: 5,
    value: 'life_changing',
  },
  {
    key: 6,
    value: 'explanatory',
  },
  {
    key: 7,
    value: 'important',
  },
  {
    key: 8,
    value: 'helpful',
  },
  {
    key: 9,
    value: 'life_saving',
  },
  {
    key: 10,
    value: 'must_read',
  },
  {
    key: 11,
    value: 'every_year',
  },
  {
    key: 12,
    value: 'very_important',
  },
  {
    key: 13,
    value: 'essential',
  },
  {
    key: 14,
    value: 'remarkable',
  },
];

export const CoachingFeedbackOptions = [
  {
    key: 'guide',
    icon: 'directions',
    width: 150,
  },
  {
    key: 'task',
    icon: 'tasks',
    width: 150,
  },
  {
    key: 'hardass',
    icon: 'stopwatch',
    width: 150,
  },
  {
    key: 'cheerleader',
    icon: 'megaphone',
    width: 150,
  },
  {
    key: 'handshake',
    icon: 'handshake',
    width: 150,
  },
  {
    key: 'accountability',
    icon: 'people-arrows',
    width: 150,
  },
  {
    key: 'contract',
    icon: 'pen-nib',
    width: 250,
  },
];

export const ComfortingPreferences = [
  'listened_to',
  'reassurance',
  'my_feeling',
  'solution',
  'humor',
  'hug',
  'hearing_optimism',
  'hearing_pessimism',
  'conversation',
  'other_people',
  'alone',
];

export const stressRecoveries = ['tea', 'exercise', 'meditating', 'music'];

export const ResourcesRoots = [
  {
    key: 'recommend',
    icon: 'hand-holding-seedling',
  },
  {
    key: 'social',
    icon: 'users',
  },
  {
    key: 'me',
    icon: 'user',
  },
  {
    key: 'bookmark',
    icon: 'bookmark',
  },
];

export const ResourceContentRoots = [
  {
    key: 'books',
    icon: 'book',
  },
  {
    key: 'blogs',
    icon: 'rss-square',
  },
  {
    key: 'podcasts',
    icon: 'podcast',
  },
  {
    key: 'class',
    icon: 'users-class',
  },
  {
    key: 'video',
    icon: 'video',
  },
];

export const EmptyChallenge = {
  title: '',
  challenges: [],
  duration: 7,
  teammates: [],
  skills: [],
};

export const TemplateDailyChallenges = [
  {
    category: 'eating',
    measures: ['1_meal', '2_meal', '3_meal', 'every_meal'],
  },
  {
    category: 'sleep',
    measures: ['1_extra_hour', '2_extra_hour', '3_extra_hour', 'Natural'],
  },
  {
    category: 'hydrating',
    measures: ['4_6', '6_plus'],
  },
  {
    category: 'exercising',
    measures: [
      '10_pushups',
      '50_pushups',
      '10_sit_ups',
      '50_sit_ups',
      'walk',
      'jog',
      'yoga',
    ],
  },
  {
    category: 'meditation',
    measures: [
      '1_minute',
      '4_minutes',
      '10_minutes',
      '20_minutes',
      '30_minutes',
      '1_hour',
    ],
  },
  {
    category: 'self-compassion',
    measures: ['15_minutes', '30_minutes', 'metta_practice'],
  },
  {
    category: 'gratitude',
    measures: ['gratitude_journal'],
  },
  {
    category: 'writing',
    measures: [
      'daily_journaling',
      '10_minutes',
      '20_minutes',
      '30_minutes',
      '1_hour',
      '1_poem',
    ],
  },
  {
    category: 'reading',
    measures: [
      '10_pages',
      '25_pages',
      '100_pages',
      '1_book',
      '10_books',
      '100_books',
    ],
  },
  {
    category: 'intermittent-fasting',
    measures: ['8_hours', '10_hours', '16_hours'],
  },
  {
    category: 'cold-exposure',
    measures: ['cold_shower'],
  },
];

export const TemplateChallenges = [
  {
    index: 1,
    title: '#75Hard',
    challenges: [
      {category: 'eating', measure: 'every_meal'},
      {category: 'hydrating', measure: '4_6'},
      {category: 'exercising', measure: '50_pushups'},
      {category: 'reading', measure: '100_pages'},
    ],
    duration: 75,
    skills: ['grit', 'pain-tolerance'],
  },
  {
    index: 2,
    title: '#25Hard',
    challenges: [
      {category: 'eating', measure: 'every_meal'},
      {category: 'hydrating', measure: '6_plus'},
      {category: 'exercising', measure: '50_pushups'},
      {category: 'reading', measure: '100_pages'},
    ],
    duration: 25,
    skills: ['grit', 'pain-tolerance'],
  },
  {
    index: 3,
    title: '#Mindful10',
    challenges: [
      {category: 'gratitude', measure: 'gratitude_journal'},
      {category: 'writing', measure: '20_minutes'},
      {category: 'eating', measure: '2_meal'},
      {category: 'hydrating', measure: '4_6'},
    ],
    duration: 10,
    skills: ['grit', 'pain-tolerance'],
  },
  {
    index: 4,
    title: '#Mindful30',
    challenges: [
      {category: 'gratitude', measure: 'gratitude_journal'},
      {category: 'writing', measure: '30_minutes'},
      {category: 'eating', measure: '3_meal'},
      {category: 'hydrating', measure: '4_6'},
    ],
    duration: 30,
    skills: ['grit', 'pain-tolerance'],
  },
];

export const ChallengeIconData = {
  custom: 'mountain',
  eating: 'carrot',
  sleep: 'bed',
  hydrating: 'glass',
  exercising: 'running',
  meditation: 'praying-hands',
  'self-compassion': 'heart',
  gratitude: 'hands-heart',
  writing: 'pencil',
  reading: 'book',
  'intermittent-fasting': 'tachometer-slowest',
  'cold-exposure': 'snowflakes',
};
